Fix issue 125 add group management methods
citahub/cita-sdk-java pull request #137
Opened 2019-08-26 12:18 UTC by yangzhenlong

fix move the initialization of sysControl object to the static block.
add GroupManagerExample and move queryGroup method from SystemContractExample to GroupManagerExample. 
add unit testing of newGroup interface

2019-08-26 12:53 UTC, rainchen commented on core/src/main/java/com/cryptape/cita/protocol/system/CITAjSystemContract.java
> +     * @throws IOException
should add `@return`

2019-08-26 12:55 UTC, rainchen commented on tests/src/main/java/com/cryptape/cita/tests/GroupManagerExample.java
> + * @date: 2019-08-26 17:46
remove the `@author` and `@date` since we already have git history

2019-08-26 12:56 UTC, rainchen commented on core/src/main/java/com/cryptape/cita/protocol/system/CITAjSystemContract.java
> +        //account addresses convert to Address object list
should add a space after `//`

2019-08-26 13:01 UTC, rainchen commented on core/src/main/java/com/cryptape/cita/protocol/system/CITAjSystemContract.java
> +     * @see <a href="https://docs.citahub.com/zh-CN/cita/sys-contract-interface/interface#newgroup">newGroup</a>
nice comment

2019-08-26 13:04 UTC, rainchen requested changes
please update

2019-08-27 01:35 UTC, yangzhenlong commented on core/src/main/java/com/cryptape/cita/protocol/system/CITAjSystemContract.java
> +        //account addresses convert to Address object list
Thank you for your advice. I see.

2019-08-27 09:28 UTC, rainchen approved these changes

2019-08-27 09:29 UTC, rainchen commented
@UDLD review PR

2019-08-27 10:30 UTC, UDLD commented on core/src/main/java/com/cryptape/cita/protocol/system/CITAjSystemContract.java
> +        String txHash = CITASystemContract.sendTxAndGetHash(
No problem， but you should know sendTxAndGetHash method just support sha256 algorithm.

2019-08-27 10:30 UTC, UDLD approved these changes

2019-08-27 10:33 UTC, merged