add introduction document
citahub/cita-sdk-java pull request #138
Opened 2019-08-27 08:21 UTC by yangzhenlong

add introduction document

2019-08-27 10:34 UTC, rainchen commented on README.md
> +### 报告Bug
注意排版，### 前要有空行

2019-08-28 02:40 UTC, rainchen requested changes
please update

2019-08-28 07:15 UTC, UDLD approved these changes

2019-08-28 13:10 UTC, rainchen approved these changes

2019-08-28 13:10 UTC, rainchen commented
@yangzhenlong 
> This branch is out-of-date with the base branch
> Merge the latest changes from develop into this branch.

please update

2019-09-18 06:41 UTC, merged